language: java

jdk:
  - openjdk8

install: true
script: mvn clean install -DskipTests=true

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379

after_success:
  - mvn test jacoco:report coveralls:report